require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LunchDatesController do

  # This should return the minimal set of attributes required to create a valid
  # LunchDate. As you add validations to LunchDate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LunchDatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lunch_dates as @lunch_dates" do
      lunch_date = LunchDate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lunch_dates).should eq([lunch_date])
    end
  end

  describe "GET show" do
    it "assigns the requested lunch_date as @lunch_date" do
      lunch_date = LunchDate.create! valid_attributes
      get :show, {:id => lunch_date.to_param}, valid_session
      assigns(:lunch_date).should eq(lunch_date)
    end
  end

  describe "GET new" do
    it "assigns a new lunch_date as @lunch_date" do
      get :new, {}, valid_session
      assigns(:lunch_date).should be_a_new(LunchDate)
    end
  end

  describe "GET edit" do
    it "assigns the requested lunch_date as @lunch_date" do
      lunch_date = LunchDate.create! valid_attributes
      get :edit, {:id => lunch_date.to_param}, valid_session
      assigns(:lunch_date).should eq(lunch_date)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LunchDate" do
        expect {
          post :create, {:lunch_date => valid_attributes}, valid_session
        }.to change(LunchDate, :count).by(1)
      end

      it "assigns a newly created lunch_date as @lunch_date" do
        post :create, {:lunch_date => valid_attributes}, valid_session
        assigns(:lunch_date).should be_a(LunchDate)
        assigns(:lunch_date).should be_persisted
      end

      it "redirects to the created lunch_date" do
        post :create, {:lunch_date => valid_attributes}, valid_session
        response.should redirect_to(LunchDate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lunch_date as @lunch_date" do
        # Trigger the behavior that occurs when invalid params are submitted
        LunchDate.any_instance.stub(:save).and_return(false)
        post :create, {:lunch_date => {}}, valid_session
        assigns(:lunch_date).should be_a_new(LunchDate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LunchDate.any_instance.stub(:save).and_return(false)
        post :create, {:lunch_date => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lunch_date" do
        lunch_date = LunchDate.create! valid_attributes
        # Assuming there are no other lunch_dates in the database, this
        # specifies that the LunchDate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LunchDate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => lunch_date.to_param, :lunch_date => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested lunch_date as @lunch_date" do
        lunch_date = LunchDate.create! valid_attributes
        put :update, {:id => lunch_date.to_param, :lunch_date => valid_attributes}, valid_session
        assigns(:lunch_date).should eq(lunch_date)
      end

      it "redirects to the lunch_date" do
        lunch_date = LunchDate.create! valid_attributes
        put :update, {:id => lunch_date.to_param, :lunch_date => valid_attributes}, valid_session
        response.should redirect_to(lunch_date)
      end
    end

    describe "with invalid params" do
      it "assigns the lunch_date as @lunch_date" do
        lunch_date = LunchDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LunchDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => lunch_date.to_param, :lunch_date => {}}, valid_session
        assigns(:lunch_date).should eq(lunch_date)
      end

      it "re-renders the 'edit' template" do
        lunch_date = LunchDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LunchDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => lunch_date.to_param, :lunch_date => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lunch_date" do
      lunch_date = LunchDate.create! valid_attributes
      expect {
        delete :destroy, {:id => lunch_date.to_param}, valid_session
      }.to change(LunchDate, :count).by(-1)
    end

    it "redirects to the lunch_dates list" do
      lunch_date = LunchDate.create! valid_attributes
      delete :destroy, {:id => lunch_date.to_param}, valid_session
      response.should redirect_to(lunch_dates_url)
    end
  end

end
